### ISSUE TITLE
images after build are not accepted by doubleclick

### ISSUE THREAD

**Issue by pghlclem** [mediamonks/generator-richmedia-temple#20]
After you build and upload your creative to doubleclick you get an error.

eed2dd6a3d6f4937a6b7b5b2d49a4c4b.png rejected: The image file eed2dd6a3d6f4937a6b7b5b2d49a4c4b.png is invalid.
![eed2dd6a3d6f4937a6b7b5b2d49a4c4b](https://user-images.githubusercontent.com/5237794/47481507-0f379500-d834-11e8-9df7-c61c4413e364.png)

**Comment by mientjan** [comment]
fixed
