### ISSUE TITLE
When you install the generator-richmedia-temple again, it will add two lines when you want to run dev

### ISSUE THREAD

**Issue by pghlclem** [mediamonks/generator-richmedia-temple#24]
When you install the generator-richmedia-temple again, it will add two lines when you want to run dev :

? Please choose the current build to start developing.
  ALL
  ./node_modules/generator-richmedia-temple/generators/createBanner/templates/doubleclick/.richmediarc
  ./node_modules/generator-richmedia-temple/generators/createBanner/templates/netflix/.richmediarc
  ./src/300x250_alt/.richmediarc
> ./src/300x250/.richmediarc

**Comment by mientjan** [comment]
I think your not installing the generator global. But local, thats the problem you are having here @pghlclem

**Comment by mientjan** [comment]
This is fixed in richmedia-temple-server
