### ISSUE TITLE
Add an userAgent Library 

### ISSUE THREAD

**Issue by dave-tervoort** [mediamonks/generator-richmedia-temple#33]
Would be good to have an user agent library. That checks if you are on mobile, desktop or tablet. But also creates variables like isIOS or isIE.

**Comment by mientjan** [comment]
This is something for https://github.com/mediamonks/temple. Can you add it to that library?

**Comment by mientjan** [comment]
This is already there, https://github.com/mediamonks/temple/blob/master/src/util/Browser.js
