### ISSUE TITLE
netflix needs an impression

### ISSUE THREAD

**Issue by pghlclem** [mediamonks/generator-richmedia-temple#36]
Monet.logEvent("MONET_IMPRESSION", {
      type: "RICH_MEDIA",
      skills: ["SINGLE_TITLE", "VIDEO"]
    });

**Comment by mientjan** [comment]
I dont know what this means?

**Comment by mm-paulie** [comment]
for the MonetPlatformComponent.js something like this:
setImpressionPixel(type, skills) {
    return Monet.logEvent("MONET_IMPRESSION", { "type": type, "skills": skills });
  }
