### ISSUE TITLE
Add GSDevTools to new initialized unit

### ISSUE THREAD

**Issue by Simonmediamonks** [mediamonks/generator-richmedia-temple#37]
So developers can use timeline controls when developing new units.

**Comment by mientjan** [comment]
I just realized we cant add This to the library and i think you need to delete it. 
GSDevTools is from greensock club and is behind a pay wall. We cant integrate this with GSDevtools added as a library.

**Comment by Simonmediamonks** [comment]
This is meant to be internal, we still need to implement GSDevTools getting removed when we build the units. Then it should be no problem?
