### ISSUE TITLE
Generator finds wrong project name and always gives error about it

### ISSUE THREAD

**Issue by caos2k** [mediamonks/generator-richmedia-temple#54]
As you can see in the below screenshot, the folder on my computer is called
**bayer-lotrimin-digital-campaign**

but the generator says, like if it removes dashes after the first one
**Your project name (bayer-lotrimin digital campaign)**
**>> Please enter a projectName without spaces!**

![Screenshot 2019-10-01 at 16 18 55](https://user-images.githubusercontent.com/4586508/65970787-6e038680-e467-11e9-9686-97399d73a870.png)

**Comment by mm-paulie** [comment]
https://github.com/yeoman/generator/issues/556
I think this is a Yeoman issue created in determineAppname() {
> return appname.replace(/[^\w\s]+?/g, ' ');
Not sure if it can be fixed.

**Comment by mirkovw** [comment]
@mm-paulie @caos2k It was actually an issue with string.replace() only replacing the first instance of a space with a -
Fixed now! Will be published to NPM soon.
