### ISSUE TITLE
Add "the spreadsheet needs to be public" info

### ISSUE THREAD

**Issue by anamartins-mm** [mediamonks/generator-richmedia-temple#63]
On [Google Sheets section](https://github.com/mediamonks/generator-richmedia-temple/tree/gh-pages#google-sheets), it's important to say that the spreadsheet needs to be public.  Otherwise, you going to get a 403 error.

**Comment by mirkovw** [comment]
@anamartins-mm This has since been added to the documentation: https://mediamonks.github.io/display-advertising-docs/richmediarc#feeds-with-google-spreadsheet

So closing this ticket now
