### ISSUE TITLE
Change generator-richmedia-temple to generator-display-advertising

### ISSUE THREAD

**Issue by mientjan** [mediamonks/generator-richmedia-temple#71]
Change generator-richmedia-temple to generator-display-advertising

**Comment by mm-paulie** [comment]
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/renaming-a-repository
I think you, as an owner, need to change the name, since you have the rights to do so

**Comment by mirkovw** [comment]
@mientjan can you do this?
