### ISSUE TITLE
iFrame with ?test=1 for dev and build page

### ISSUE THREAD

**Issue by caos2k** [mediamonks/generator-richmedia-temple#82]
By adding **?test=1**
<iframe class="visible" src="{{src}}index.html?test=1" width="{{width}}" height="{{height}}" frameborder="0"></iframe>
to the 2 files 
- template.build.hbs (line 210)
- template.dev.hbs (line 211)

then we don't get issues on the Preview page when using FlashTalking APIs.

This won't affect other banners (doubleclick or standard)

**Comment by mirkovw** [comment]
@caos2k is this still a relevant issue?

**Comment by caos2k** [comment]
not really as we don't use Flashtalking anymore.
