### ISSUE TITLE
There is some opacity upon taking a screenshot

### ISSUE THREAD

**Issue by Trung-Dev** [mediamonks/generator-richmedia-temple#83]
![src_banners_300x250](https://user-images.githubusercontent.com/13298652/105007874-d00b4500-5a38-11eb-9a74-5fca3151f3f4.png)
<= screenshot version

![Screenshot 2021-01-19 at 09 29 38](https://user-images.githubusercontent.com/13298652/105007935-e3b6ab80-5a38-11eb-8087-2e56f6c7d6fe.png)
<= unit

**Comment by mm-paulie** [comment]
Closed #83 with a plaster fix since this is due to the preview page loading the iframe twice and therefor puppeteer can't do an exitclick directly on the banner
