### ISSUE TITLE
Feature Request: Automation of custom  npm dev- command creation

### ISSUE THREAD

**Issue by Frankie-B** [mediamonks/generator-richmedia-temple#92]
The idea:

Instead of using glob patterns and manually creating custom commands for run a dev command for a specific unit type. Could we instead have a feature that could search the .richmediarc configs, and maybe have a user prompt with a few options to allow for the automated creation of dev server commands:

`All === npm run dev-all`

`size === npm run dev-[size]`

or  maybe a specific variation

`variation === npm run dev-[variation] `

this could be useful if a project has a lot of units and you want to be able to quickly run the dev server  fo a specific type of unit(s).

**Comment by mirkovw** [comment]
@Frankie-B this is not the right repo for that :) You should add this issue to richmedia-temple-server instead.

**Comment by Frankie-B** [comment]
Ah okay sorry for that.
